# Generated by Django 5.0.6 on 2024-05-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='LabelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='BagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='عنوان در url')),
                ('text', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس')], default='p', max_length=1, verbose_name='وضعیت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='category_bag', to='bag.categorymodel', verbose_name='دسته بندی')),
                ('label', models.ManyToManyField(related_name='label_bags', to='bag.categorymodel', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'کیف',
                'verbose_name_plural': 'کیف ها',
            },
        ),
        migrations.CreateModel(
            name='ImageOfBagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/bag', verbose_name='عکس')),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bag.bagmodel', verbose_name='کیف')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس های محصول',
            },
        ),
    ]
