# Generated by Django 5.0.6 on 2024-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_alter_bagmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagmodel',
            name='category',
            field=models.ManyToManyField(related_name='category_bags', to='bag.categorymodel', verbose_name='دسته بندی'),
        ),
    ]
