# Generated by Django 5.0.6 on 2024-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_alter_bagmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagmodel',
            name='category',
            field=models.ManyToManyField(related_name='bags', to='bag.categorymodel', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='bagmodel',
            name='label',
            field=models.ManyToManyField(related_name='bags', to='bag.labelmodel', verbose_name='برچسب'),
        ),
    ]
