# Generated by Django 5.0.6 on 2024-05-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0004_alter_bagmodel_category_alter_bagmodel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagmodel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='bags', to='bag.categorymodel', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='bagmodel',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='bags', to='bag.labelmodel', verbose_name='برچسب'),
        ),
    ]
